version: '2'
services:
  rsnsales-app:
    image: rsnsales
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://rsnsales-mysql:3306/rsnsales?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  rsnsales-mysql:
    extends:
      file: mysql.yml
      service: rsnsales-mysql
  rsnsales-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: rsnsales-elasticsearch
